[package]
name = "elfdeps"
version = "0.2.0"
authors = ["odedlaz@github.com"]

[dependencies]
scroll = "0.*"
structopt = "0.*"
structopt-derive = "0.*"
goblin = "0.*"
glob = "0.*"
failure = "0.*"
regex = "0.*"
lazy_static = "1.*"
